//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyService
    {
        public CompanyService()
        {
            this.CompanyService1 = new HashSet<CompanyService>();
            this.Expenses = new HashSet<Expense>();
            this.LegalActivities = new HashSet<LegalActivity>();
        }
    
        public int CompanyServiceId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> BaseServiceGuid { get; set; }
        public Nullable<int> C_ParentId { get; set; }
    
        public virtual ICollection<CompanyService> CompanyService1 { get; set; }
        public virtual CompanyService CompanyService2 { get; set; }
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<LegalActivity> LegalActivities { get; set; }
    }
}
