//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletionAct
    {
        public int CompletionActId { get; set; }
        public string Title { get; set; }
        public string Payments { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string DealNumber { get; set; }
        public System.DateTime DealDate { get; set; }
        public System.Guid CompanyGuid { get; set; }
        public System.Guid CustomerGuid { get; set; }
        public decimal TotalValue { get; set; }
        public Nullable<double> TaxPercent { get; set; }
    }
}
