//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalEntityAddPhone
    {
        public int C_GeoLocationId { get; set; }
        public int C_LegalEntityId { get; set; }
        public string Phones { get; set; }
    
        public virtual GeoLocation GeoLocation { get; set; }
        public virtual LegalEntity LegalEntity { get; set; }
    }
}
