//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalEntity
    {
        public LegalEntity()
        {
            this.LegalEnityDetails = new HashSet<LegalEnityDetail>();
            this.GeoLocations = new HashSet<GeoLocation>();
            this.Customers = new HashSet<Customer>();
            this.LegalEntityAddPhones = new HashSet<LegalEntityAddPhone>();
        }
    
        public int LegalEntityId { get; set; }
        public string LegalName { get; set; }
        public string PublicName { get; set; }
        public string Phones { get; set; }
        public string Mails { get; set; }
        public string Sites { get; set; }
        public int C_MainGeoId { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public byte StatusId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> Assigned { get; set; }
        public System.Guid CompanyGuid { get; set; }
        public string Skype { get; set; }
        public string LogoPath { get; set; }
    
        public virtual GeoLocation GeoLocation { get; set; }
        public virtual ICollection<LegalEnityDetail> LegalEnityDetails { get; set; }
        public virtual ICollection<GeoLocation> GeoLocations { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<LegalEntityAddPhone> LegalEntityAddPhones { get; set; }
    }
}
