//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalCRMEntities : DbContext
    {
        public LocalCRMEntities()
            : base("name=LocalCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompletionAct> CompletionActs { get; set; }
        public virtual DbSet<GeoLocation> GeoLocations { get; set; }
        public virtual DbSet<LegalEnityDetail> LegalEnityDetails { get; set; }
        public virtual DbSet<LegalEntity> LegalEntities { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<MeetingTransfer> MeetingTransfers { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PaymentSchedule> PaymentSchedules { get; set; }
        public virtual DbSet<PaymentTemplate> PaymentTemplates { get; set; }
        public virtual DbSet<PaymentInvoice> PaymentInvoices { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<LegalActivity> LegalActivities { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<CompanyService> CompanyServices { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Passport> Passports { get; set; }
        public virtual DbSet<ModifyLog> ModifyLogs { get; set; }
        public virtual DbSet<TaskPeriod> TaskPeriods { get; set; }
        public virtual DbSet<TaskCategory> TaskCategories { get; set; }
        public virtual DbSet<UserNotify> UserNotifies { get; set; }
        public virtual DbSet<LegalEntityAddPhone> LegalEntityAddPhones { get; set; }
    }
}
