//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.MeetingTransfers = new HashSet<MeetingTransfer>();
        }
    
        public int MeetingId { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public int C_CustomerId { get; set; }
        public string Goals { get; set; }
        public string Comment { get; set; }
        public byte StatusId { get; set; }
        public string Calls { get; set; }
        public string ResultComment { get; set; }
        public System.Guid MeetingGuid { get; set; }
    
        public virtual ICollection<MeetingTransfer> MeetingTransfers { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
