//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTemplate
    {
        public PaymentTemplate()
        {
            this.PaymentSchedules = new HashSet<PaymentSchedule>();
        }
    
        public int PaymentTemplateId { get; set; }
        public System.Guid CompanyGuid { get; set; }
        public string Services { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
    
        public virtual ICollection<PaymentSchedule> PaymentSchedules { get; set; }
    }
}
