//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentInvoiceDetailId { get; set; }
        public decimal ItemCost { get; set; }
        public double Qty { get; set; }
        public string ServiceFullName { get; set; }
        public Nullable<int> C_InvoiceId { get; set; }
        public Nullable<int> C_PaymentId { get; set; }
        public Nullable<double> ItemTaxPercent { get; set; }
    
        public virtual PaymentInvoice PaymentInvoice { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
