//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSchedule
    {
        public int PaymentScheduleId { get; set; }
        public Nullable<int> C_PaymentTemplateId { get; set; }
        public int C_PaymentId { get; set; }
        public System.DateTime PayBefore { get; set; }
    
        public virtual PaymentTemplate PaymentTemplate { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
