//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskPeriod
    {
        public System.Guid TaskPeriodId { get; set; }
        public System.Guid TaskTicketId { get; set; }
        public byte PeriodType { get; set; }
        public System.DateTime DateStarted { get; set; }
        public byte StatusId { get; set; }
        public Nullable<System.TimeSpan> NotifyBefore { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> Assigned { get; set; }
        public int AddNumber { get; set; }
    }
}
