//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLocalContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotify
    {
        public int HistoryItemId { get; set; }
        public string Text { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsViewed { get; set; }
        public System.Guid User4Notify { get; set; }
        public System.DateTime NotifyAfter { get; set; }
        public Nullable<System.Guid> InitByUserId { get; set; }
        public string ObjectId { get; set; }
    }
}
