//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMAction
    {
        public int Id { get; set; }
        public string UrlID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string RequestUrl { get; set; }
        public System.Guid UserId { get; set; }
        public string ActionData { get; set; }
        public System.DateTime TimeExecute { get; set; }
        public long DurationExecuting { get; set; }
        public Nullable<System.DateTime> TimeResult { get; set; }
        public Nullable<long> DurationResultExecuting { get; set; }
        public Nullable<System.DateTime> ClientTimestamp { get; set; }
        public string ClientIP { get; set; }
        public string ActionDescription { get; set; }
        public Nullable<int> ResponseCode { get; set; }
        public string ErrorMessage { get; set; }
    }
}
