//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public string Object { get; set; }
        public int Level { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Date { get; set; }
        public string EventData { get; set; }
        public Nullable<int> EventType { get; set; }
        public string CustomEventType { get; set; }
        public int JournalID { get; set; }
    
        public virtual JournalEvent JournalEvent { get; set; }
    }
}
