//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsListener
    {
        public int ProfileId { get; set; }
        public Nullable<int> EventType { get; set; }
        public int ListenerId { get; set; }
        public bool IsActive { get; set; }
        public int NotifyType { get; set; }
        public string CustomEventType { get; set; }
    
        public virtual Listener Listener { get; set; }
    }
}
