//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalsListener
    {
        public int RecordId { get; set; }
        public int ListenerId { get; set; }
        public int JournalId { get; set; }
        public bool IsAccess { get; set; }
        public bool IsNotify { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual JournalEvent JournalEvent { get; set; }
        public virtual Listener Listener { get; set; }
    }
}
