//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEvent
    {
        public JournalEvent()
        {
            this.Events = new HashSet<Event>();
            this.JournalsListeners = new HashSet<JournalsListener>();
        }
    
        public int JournalId { get; set; }
        public string Name { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<byte> LevelRegistration { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<JournalsListener> JournalsListeners { get; set; }
    }
}
