//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listener
    {
        public Listener()
        {
            this.EventsListeners = new HashSet<EventsListener>();
            this.JournalsListeners = new HashSet<JournalsListener>();
            this.Notify4Listener = new HashSet<Notify4Listener>();
        }
    
        public int ListenerId { get; set; }
        public System.Guid UserID { get; set; }
        public string PhoneContact { get; set; }
        public string MailContact { get; set; }
        public string NameContact { get; set; }
    
        public virtual ICollection<EventsListener> EventsListeners { get; set; }
        public virtual ICollection<JournalsListener> JournalsListeners { get; set; }
        public virtual ICollection<Notify4Listener> Notify4Listener { get; set; }
    }
}
