//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogEntities : DbContext
    {
        public LogEntities()
            : base("name=LogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRMAction> CRMActions { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventsListener> EventsListeners { get; set; }
        public virtual DbSet<JournalEvent> JournalEvents { get; set; }
        public virtual DbSet<JournalsListener> JournalsListeners { get; set; }
        public virtual DbSet<Listener> Listeners { get; set; }
        public virtual DbSet<MailRegistration> MailRegistrations { get; set; }
        public virtual DbSet<Notify> Notifies { get; set; }
        public virtual DbSet<Notify4Listener> Notify4Listener { get; set; }
        public virtual DbSet<NotifyHistory> NotifyHistories { get; set; }
    }
}
