//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailRegistration
    {
        public int MailRegistrationId { get; set; }
        public bool IsSuccess { get; set; }
        public System.DateTime Created { get; set; }
        public string Name { get; set; }
        public System.Guid rowguid { get; set; }
        public string RegisterCode { get; set; }
        public string ResponseCode { get; set; }
    }
}
