//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notify
    {
        public Notify()
        {
            this.Notify4Listener = new HashSet<Notify4Listener>();
        }
    
        public int NotifyId { get; set; }
        public string Name { get; set; }
        public byte NotifyObjectCategory { get; set; }
    
        public virtual ICollection<Notify4Listener> Notify4Listener { get; set; }
    }
}
