//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notify4Listener
    {
        public Notify4Listener()
        {
            this.NotifyHistories = new HashSet<NotifyHistory>();
        }
    
        public int Notify4ListenerId { get; set; }
        public int C_NotifyId { get; set; }
        public int C_ListenerId { get; set; }
        public bool IsAvailable { get; set; }
        public bool FromMe { get; set; }
        public bool ToMe { get; set; }
        public bool UnderMe { get; set; }
    
        public virtual Listener Listener { get; set; }
        public virtual Notify Notify { get; set; }
        public virtual ICollection<NotifyHistory> NotifyHistories { get; set; }
    }
}
