//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCookie
    {
        public int CookieId { get; set; }
        public int AppId { get; set; }
        public System.Guid UserId { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Expired { get; set; }
        public string IpAddress { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
    }
}
