//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionalRole
    {
        public FunctionalRole()
        {
            this.FunctionalRole1 = new HashSet<FunctionalRole>();
            this.UserFunctionalRoles = new HashSet<UserFunctionalRole>();
        }
    
        public int RoleId { get; set; }
        public string Name { get; set; }
        public bool IsAvailable { get; set; }
        public string IncludeRoles { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsCRM { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<FunctionalRole> FunctionalRole1 { get; set; }
        public virtual FunctionalRole FunctionalRole2 { get; set; }
        public virtual ICollection<UserFunctionalRole> UserFunctionalRoles { get; set; }
    }
}
