//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule4Role
    {
        public int RelationId { get; set; }
        public int RuleId { get; set; }
        public int RoleId { get; set; }
        public bool IsAvailable { get; set; }
        public bool Create { get; set; }
        public bool Read { get; set; }
        public bool Update { get; set; }
        public bool Delete { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Rule Rule { get; set; }
    }
}
