//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AppCookies = new HashSet<AppCookie>();
            this.AuthStats = new HashSet<AuthStat>();
            this.UserFunctionalRoles = new HashSet<UserFunctionalRole>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public System.Guid UserId { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public string Pass { get; set; }
        public bool IsOnline { get; set; }
        public Nullable<System.DateTime> Expired { get; set; }
        public string Salt { get; set; }
        public bool IsBlocked { get; set; }
        public string Login { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string WorkPhone { get; set; }
        public string OpenId { get; set; }
        public string AuthKey { get; set; }
        public string PhoneKey { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<bool> IsTemporaryAbsent { get; set; }
        public string AbsentReason { get; set; }
        public string AvailableIps { get; set; }
        public Nullable<System.Guid> RemoteToken { get; set; }
    
        public virtual ICollection<AppCookie> AppCookies { get; set; }
        public virtual ICollection<AuthStat> AuthStats { get; set; }
        public virtual ICollection<UserFunctionalRole> UserFunctionalRoles { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
