//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int ProfileId { get; set; }
        public System.Guid C_UserId { get; set; }
        public int C_RoleId { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
