//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserEntities : DbContext
    {
        public UserEntities()
            : base("name=UserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCookie> AppCookies { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<AuthStat> AuthStats { get; set; }
        public virtual DbSet<FunctionalRole> FunctionalRoles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Rule4Role> Rule4Role { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserFunctionalRole> UserFunctionalRoles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
    }
}
