//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CssCategory
    {
        public int CssCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CssStyles { get; set; }
        public int C_TemplateId { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
