//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public Gallery()
        {
            this.PasteBoardPages = new HashSet<PasteBoardPage>();
            this.Images = new HashSet<Image>();
        }
    
        public int GalleryId { get; set; }
        public string Name { get; set; }
        public string ItemsPath { get; set; }
        public bool IsSlider { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<PasteBoardPage> PasteBoardPages { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
