//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageId { get; set; }
        public string Path { get; set; }
        public string Alt { get; set; }
        public string Title { get; set; }
        public int C_GalleryId { get; set; }
        public Nullable<int> C_SlideSettingId { get; set; }
    
        public virtual Gallery Gallery { get; set; }
        public virtual SlideSetting SlideSetting { get; set; }
    }
}
