//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingTemplate
    {
        public LandingTemplate()
        {
            this.LandingBlocks = new HashSet<LandingBlock>();
            this.LandingPages = new HashSet<LandingPage>();
        }
    
        public int TemplateId { get; set; }
        public string TemplateName { get; set; }
        public int TypeId { get; set; }
    
        public virtual ICollection<LandingBlock> LandingBlocks { get; set; }
        public virtual ICollection<LandingPage> LandingPages { get; set; }
    }
}
