//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingBlock
    {
        public LandingBlock()
        {
            this.PageBlocks = new HashSet<PageBlock>();
        }
    
        public int LandingBlockId { get; set; }
        public string BlockName { get; set; }
        public int C_TemplateId { get; set; }
    
        public virtual LandingTemplate LandingTemplate { get; set; }
        public virtual ICollection<PageBlock> PageBlocks { get; set; }
    }
}
