//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingPage
    {
        public LandingPage()
        {
            this.PageBlocks = new HashSet<PageBlock>();
            this.PageSettings = new HashSet<PageSetting>();
        }
    
        public int LandingPageId { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime Created { get; set; }
        public int C_TemplateId { get; set; }
        public int C_ProjectClientId { get; set; }
        public string Allias { get; set; }
        public string Domain { get; set; }
    
        public virtual LandingTemplate LandingTemplate { get; set; }
        public virtual ICollection<PageBlock> PageBlocks { get; set; }
        public virtual ICollection<PageSetting> PageSettings { get; set; }
        public virtual ProjectClient ProjectClient { get; set; }
    }
}
