//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingPageView
    {
        public string Allias { get; set; }
        public int LandingPageId { get; set; }
        public string TemplateName { get; set; }
        public int TypeId { get; set; }
        public int C_TemplateId { get; set; }
        public int C_ProjectClientId { get; set; }
        public System.DateTime Created { get; set; }
        public string BlockOrder { get; set; }
        public string DisabledBlocks { get; set; }
        public string CustomCssRoute { get; set; }
        public System.DateTime AvailableTo { get; set; }
        public bool IsAvailable { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long Phone { get; set; }
        public System.DateTime ProjectCreated { get; set; }
    }
}
