//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LandingEntities : DbContext
    {
        public LandingEntities()
            : base("name=LandingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LandingBlock> LandingBlocks { get; set; }
        public virtual DbSet<LandingPage> LandingPages { get; set; }
        public virtual DbSet<LandingTemplate> LandingTemplates { get; set; }
        public virtual DbSet<PageBlock> PageBlocks { get; set; }
        public virtual DbSet<PageSetting> PageSettings { get; set; }
        public virtual DbSet<ProjectClient> ProjectClients { get; set; }
        public virtual DbSet<LandingPageView> LandingPageViews { get; set; }
    }
}
