//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageSetting
    {
        public int PageSettingsId { get; set; }
        public string BlockOrder { get; set; }
        public string DisabledBlocks { get; set; }
        public string CustomCssRoute { get; set; }
        public System.DateTime AvailableTo { get; set; }
        public bool IsAvailable { get; set; }
        public int C_LandingPageId { get; set; }
    
        public virtual LandingPage LandingPage { get; set; }
    }
}
