//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PasteboardEntities : DbContext
    {
        public PasteboardEntities()
            : base("name=PasteboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PasteBoardSetting> PasteBoardSettings { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<SeoItem> SeoItems { get; set; }
        public virtual DbSet<PasteBoardPage> PasteBoardPages { get; set; }
        public virtual DbSet<SlideSetting> SlideSettings { get; set; }
        public virtual DbSet<Image> Images { get; set; }
    }
}
