//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasteBoardPage
    {
        public PasteBoardPage()
        {
            this.PasteBoardPage1 = new HashSet<PasteBoardPage>();
        }
    
        public int PasteBoardPageId { get; set; }
        public string PageContent { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsMenuItem { get; set; }
        public bool IsHtml { get; set; }
        public bool IsSocialRepost { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<int> C_GalleryId { get; set; }
        public int C_SeoItemId { get; set; }
        public int C_SettingsId { get; set; }
        public Nullable<int> C_ParentPageId { get; set; }
        public string Notice { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Gallery Gallery { get; set; }
        public virtual ICollection<PasteBoardPage> PasteBoardPage1 { get; set; }
        public virtual PasteBoardPage PasteBoardPage2 { get; set; }
        public virtual PasteBoardSetting PasteBoardSetting { get; set; }
        public virtual SeoItem SeoItem { get; set; }
    }
}
