//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectClient
    {
        public ProjectClient()
        {
            this.LandingPages = new HashSet<LandingPage>();
        }
    
        public int ProjectClientId { get; set; }
        public System.Guid rowguid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long Phone { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ICollection<LandingPage> LandingPages { get; set; }
    }
}
