//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideSetting
    {
        public SlideSetting()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int SlideSettingsId { get; set; }
        public string HtmlContent { get; set; }
        public string UrlRedirect { get; set; }
        public bool IsBlank { get; set; }
        public int Position { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
    }
}
