//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructorLandingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.CssCategories = new HashSet<CssCategory>();
        }
    
        public int TemplateId { get; set; }
        public string Name { get; set; }
        public string LayoutName { get; set; }
        public string SourcePath { get; set; }
        public System.Guid TemplateGuid { get; set; }
        public byte Type { get; set; }
    
        public virtual ICollection<CssCategory> CssCategories { get; set; }
    }
}
