//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.GeoLocations = new HashSet<GeoLocation>();
        }
    
        public int CityId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public System.Guid CityGuid { get; set; }
        public Nullable<int> C_DistrictId { get; set; }
    
        public virtual ICollection<GeoLocation> GeoLocations { get; set; }
        public virtual District District { get; set; }
    }
}
