//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyService
    {
        public CompanyService()
        {
            this.CompanyServiceChilds = new HashSet<CompanyService>();
            this.LegalActivities = new HashSet<LegalActivity>();
        }
    
        public int CompanyServiceId { get; set; }
        public string Name { get; set; }
        public Nullable<int> C_ParentId { get; set; }
        public System.Guid ServiceGuid { get; set; }
    
        public virtual ICollection<CompanyService> CompanyServiceChilds { get; set; }
        public virtual CompanyService CompanyServiceParent { get; set; }
        public virtual ICollection<LegalActivity> LegalActivities { get; set; }
    }
}
