//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public System.Guid CustomerGuid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Position { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public bool IsLPR { get; set; }
        public bool IsAcctual { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> PossibleUserId { get; set; }
        public string SocialsLinks { get; set; }
        public string Skype { get; set; }
        public Nullable<int> C_LegalEntityId { get; set; }
        public Nullable<int> C_PassportId { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> C_GeoLocationId { get; set; }
    
        public virtual LegalEntity LegalEntity { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual GeoLocation GeoLocation { get; set; }
    }
}
