//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Cities = new HashSet<City>();
        }
    
        public int DistrictId { get; set; }
        public string Name { get; set; }
        public Nullable<int> C_CenterGeoId { get; set; }
    
        public virtual GeoLocation GeoLocation { get; set; }
        public virtual ICollection<City> Cities { get; set; }
    }
}
