//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoLocationCityView
    {
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public int GeoLocationId { get; set; }
        public Nullable<int> C_DistrictId { get; set; }
        public int CityId { get; set; }
        public System.Guid CityGuid { get; set; }
    }
}
