//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoLocation
    {
        public GeoLocation()
        {
            this.Districts = new HashSet<District>();
            this.LegalEnityDetails = new HashSet<LegalEnityDetail>();
            this.LegalEntities = new HashSet<LegalEntity>();
            this.LegalEntities1 = new HashSet<LegalEntity>();
            this.Customers = new HashSet<Customer>();
            this.LegalEntityAddPhones = new HashSet<LegalEntityAddPhone>();
            this.LegalLocationPhones = new HashSet<LegalLocationPhone>();
        }
    
        public int GeoLocationId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
        public int C_CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<LegalEnityDetail> LegalEnityDetails { get; set; }
        public virtual ICollection<LegalEntity> LegalEntities { get; set; }
        public virtual ICollection<LegalEntity> LegalEntities1 { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<LegalEntityAddPhone> LegalEntityAddPhones { get; set; }
        public virtual ICollection<LegalLocationPhone> LegalLocationPhones { get; set; }
    }
}
