//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalEnityDetail
    {
        public LegalEnityDetail()
        {
            this.LegalEntities = new HashSet<LegalEntity>();
        }
    
        public int LegalEntityDetailId { get; set; }
        public bool IsActive { get; set; }
        public long INN { get; set; }
        public long KPP { get; set; }
        public long OGRN { get; set; }
        public long RS { get; set; }
        public Nullable<long> KS { get; set; }
        public Nullable<long> BIK { get; set; }
        public int C_LegalEntityId { get; set; }
        public Nullable<int> C_GeoId { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string PayLocation { get; set; }
        public Nullable<long> PayLocationRS { get; set; }
    
        public virtual LegalEntity LegalEntity { get; set; }
        public virtual ICollection<LegalEntity> LegalEntities { get; set; }
        public virtual GeoLocation GeoLocation { get; set; }
    }
}
