//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalActivity
    {
        public int LegalActivityId { get; set; }
        public string ServiceFullName { get; set; }
        public int C_LegalEntityId { get; set; }
        public int C_ServiceId { get; set; }
    
        public virtual LegalEntity LegalEntity { get; set; }
        public virtual CompanyService CompanyService { get; set; }
    }
}
