//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalCopy
    {
        public int LegalCopyId { get; set; }
        public int C_LegalEntityId { get; set; }
        public System.Guid CopyBy { get; set; }
        public System.DateTime CopyDate { get; set; }
    
        public virtual LegalEntity LegalEntity { get; set; }
    }
}
