//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalEntityShortView
    {
        public string PublicName { get; set; }
        public int LegalEntityId { get; set; }
        public int C_MainGeoId { get; set; }
        public Nullable<int> C_CurrentLegalDetailId { get; set; }
        public System.Guid LegalEntityGuid { get; set; }
    }
}
