//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public Passport()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int PassportId { get; set; }
        public int Serial { get; set; }
        public int Number { get; set; }
        public string WhoIssue { get; set; }
        public System.DateTime DateIssue { get; set; }
        public string CodeIssue { get; set; }
        public string BirthLocation { get; set; }
        public string RegLocation { get; set; }
        public string ScanPath { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
