//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Companies = new HashSet<Company>();
            this.LegalEntities = new HashSet<LegalEntity>();
        }
    
        public int AddrId { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int Number { get; set; }
        public string AddNumber { get; set; }
        public string Phones { get; set; }
        public string Emails { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitiude { get; set; }
        public bool IsActive { get; set; }
        public int C_CompanyId { get; set; }
        public System.Guid CityGuid { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<LegalEntity> LegalEntities { get; set; }
    }
}
