//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Addresses = new HashSet<Address>();
            this.Departments = new HashSet<Department>();
            this.LegalEntities = new HashSet<LegalEntity>();
            this.WorkGroups = new HashSet<WorkGroup>();
            this.WebSites = new HashSet<WebSite>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string ShortComanyName { get; set; }
        public Nullable<int> C_CurrentAddrId { get; set; }
        public Nullable<int> C_CurrentLegalEntityId { get; set; }
        public string PhototPath { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string ICQ { get; set; }
        public string Skype { get; set; }
        public string SiteUrl { get; set; }
        public string Services { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsPublic { get; set; }
        public string LocalDB { get; set; }
        public Nullable<System.Guid> CRMGuid { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Address Address { get; set; }
        public virtual LegalEntity LegalEntity { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<LegalEntity> LegalEntities { get; set; }
        public virtual ICollection<WorkGroup> WorkGroups { get; set; }
        public virtual ICollection<WebSite> WebSites { get; set; }
    }
}
