//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyViewEntities : DbContext
    {
        public CompanyViewEntities()
            : base("name=CompanyViewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PositionInDepartmentView> PositionInDepartmentView { get; set; }
        public virtual DbSet<UserInCompanyView> UserInCompanyView { get; set; }
        public virtual DbSet<UserInDepartmentView> UserInDepartmentView { get; set; }
    }
}
