//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Positions = new HashSet<Position>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int DepartmentId { get; set; }
        public int C_CompanyId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public string WorkGroups { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Position> Positions { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
