//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTimesheet
    {
        public int EmployeeTimesheetId { get; set; }
        public int C_EmployeeId { get; set; }
        public System.DateTime Created { get; set; }
        public System.TimeSpan BeginWork { get; set; }
        public string IpLocationBegin { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string IpLocationEnd { get; set; }
        public string Comment { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
