//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionInDepartmentView
    {
        public int PositionId { get; set; }
        public string Name { get; set; }
        public string NameGenetive { get; set; }
        public string Title { get; set; }
        public string CompanyName { get; set; }
        public int C_CompanyId { get; set; }
        public int C_DepartmentId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> C_ParentPosId { get; set; }
    }
}
