//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimesheetBreak
    {
        public int TimesheetBreakId { get; set; }
        public System.DateTime DateStarted { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public byte TypeReasonId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> C_EmployeeTimesheetId { get; set; }
    
        public virtual EmployeeTimesheet EmployeeTimesheet { get; set; }
    }
}
