//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInCompanyView
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public System.Guid UserId { get; set; }
        public string CompanyName { get; set; }
        public int EmployeeId { get; set; }
        public int CompanyId { get; set; }
        public bool IsKeyEmployee { get; set; }
        public bool IsDismissed { get; set; }
        public Nullable<System.Guid> CRMGuid { get; set; }
        public string LocalDB { get; set; }
    }
}
