//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInDepartmentView
    {
        public int C_CompanyId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string FullNameGenitive { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PhotoPath { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime LastLogin { get; set; }
        public bool IsDismissed { get; set; }
        public string SocialLinks { get; set; }
        public bool IsActive { get; set; }
        public string CompanyName { get; set; }
        public bool IsKeyEmployee { get; set; }
        public Nullable<int> C_PosId { get; set; }
        public int EmployeeId { get; set; }
        public int DepartmentId { get; set; }
        public string NameGenetive { get; set; }
        public string Name { get; set; }
        public string PositiveMention { get; set; }
        public string NegativeMention { get; set; }
        public Nullable<int> C_PassportId { get; set; }
        public string WorkGroups { get; set; }
        public string DepartmentWorkGroup { get; set; }
        public Nullable<int> C_GroupHeaderId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<double> TransactionPercent { get; set; }
        public string Skype { get; set; }
        public string ICQ { get; set; }
    }
}
