//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSite
    {
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public string Url { get; set; }
        public System.Guid SiteGuid { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public byte Type { get; set; }
        public string DbSource { get; set; }
        public int C_CompanyId { get; set; }
        public string TemplateName { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
