//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkGroup
    {
        public WorkGroup()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int WorkGroupId { get; set; }
        public string Name { get; set; }
        public string Descritption { get; set; }
        public int C_CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
