//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallTicketsQuery
    {
        public System.Guid CallTicketQueryId { get; set; }
        public Nullable<System.Guid> CallTicketId { get; set; }
        public Nullable<System.Guid> WorkflowId { get; set; }
        public Nullable<System.Guid> UserIdLock { get; set; }
        public Nullable<bool> IsNonePreview { get; set; }
    }
}
