//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallTicket
    {
        public CallTicket()
        {
            this.CallTicket1 = new HashSet<CallTicket>();
        }
    
        public System.Guid CallTicketId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> Assigned { get; set; }
        public string CallTicketNumber { get; set; }
        public byte CallStatus { get; set; }
        public System.DateTime DateStarted { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> CustomerGuid { get; set; }
        public Nullable<System.Guid> PrevCallId { get; set; }
    
        public virtual ICollection<CallTicket> CallTicket1 { get; set; }
        public virtual CallTicket CallTicket2 { get; set; }
    }
}
