//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentEnclosure
    {
        public System.Guid EnclosureId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int Type { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> C_CommentId { get; set; }
        public System.Guid C_PossibleCommentId { get; set; }
    }
}
