//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryStatu
    {
        public int QueryStatusId { get; set; }
        public System.Guid QueryItemId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string CustomStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> OwnerId { get; set; }
    }
}
