//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketMaster
    {
        public System.Guid MasterId { get; set; }
        public string MasterType { get; set; }
        public Nullable<System.Guid> InstanceWfId { get; set; }
    }
}
