//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketFollower
    {
        public int FollowerId { get; set; }
        public System.Guid TicketId { get; set; }
        public string UserIds { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
