//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketFollowers = new HashSet<TicketFollower>();
            this.TicketGroups = new HashSet<TicketGroup>();
        }
    
        public System.Guid TicketId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> Assigned { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.Guid> MasterIdFK { get; set; }
        public Nullable<byte> TicketStatus { get; set; }
        public Nullable<byte> Priory { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> CustomCategoryId { get; set; }
    
        public virtual ICollection<TicketFollower> TicketFollowers { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<TicketGroup> TicketGroups { get; set; }
    }
}
