//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketEntities : DbContext
    {
        public TicketEntities()
            : base("name=TicketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommentBody> CommentBodies { get; set; }
        public virtual DbSet<CommentEnclosure> CommentEnclosures { get; set; }
        public virtual DbSet<QueryStatu> QueryStatus { get; set; }
        public virtual DbSet<TicketFollower> TicketFollowers { get; set; }
        public virtual DbSet<TicketMaster> TicketMasters { get; set; }
        public virtual DbSet<TicketsQuery> TicketsQueries { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CallTicket> CallTickets { get; set; }
        public virtual DbSet<CallTicketsQuery> CallTicketsQueries { get; set; }
        public virtual DbSet<TicketGroup> TicketGroups { get; set; }
    }
}
